INSERT INTO `business_category` (`id`, `name`, `content`) VALUES
(1, 'Fashion', 'Fashion Business is a Business that sells clothes and other related products such as shoes'),
(2, 'Electronics', 'Fashion Business is a Business that sells clothes and other related products such as shoes'),
(3, 'Technology', 'Fashion Business is a Business that sells clothes and other related products such as shoes'),
(4, 'sauna & massage', 'Fashion Business is a Business that sells clothes and other related products such as shoes'),
(5, 'Saloon', 'Fashion Business is a Business that sells clothes and other related products such as shoes'),
(6, 'Bank Services', 'Fashion Business is a Business that sells clothes and other related products such as shoes'),
(7, 'Education', 'Fashion Business is a Business that sells clothes and other related products such as shoes');


INSERT INTO `product_category` (`id`, `name`, `content`,`classification`) VALUES
(1, 'kids-activities', 'Fashion Business is a Business that sells clothes and other related products such as shoes','local'),
(2, 'wedding-parties', 'Fashion Business is a Business that sells clothes and other related products such as shoes','local'),
(3, 'cinema', 'Fashion Business is a Business that sells clothes and other related products such as shoes',''),
(4, 'salon', 'Fashion Business is a Business that sells clothes and other related products such as shoes',''),
(5, 'supplier', 'Fashion Business is a Business that sells clothes and other related products such as shoes',''),
(6, 'learing', 'Fashion Business is a Business that sells clothes and other related products such as shoes','local'),
(7, 'women-fashion', 'Fashion Business is a Business that sells clothes and other related products such as shoes','goods'),
(8, 'sport', 'Fashion Business is a Business that sells clothes and other related products such as shoes','goods'),
(9, 'gateways', 'Fashion Business is a Business that sells clothes and other related products such as shoes','gateways'),
(10, 'health-fitness', 'Fashion Business is a Business that sells clothes and other related products such as shoes','local'),
(11, 'hardware-stores-furniture', 'Fashion Business is a Business that sells clothes and other related products such as shoes','goods'),
(12, 'home-service', 'Fashion Business is a Business that sells clothes and other related products such as shoes','goods'),
(13, 'kid-babies', 'Fashion Business is a Business that sells clothes and other related products such as shoes','goods'),
(14, 'east-africa', 'Fashion Business is a Business that sells clothes and other related products such as shoes','goods'),
(15, 'apps', 'Fashion Business is a Business that sells clothes and other related products such as shoes','gateways'),
(16, 'kitchen-dining', 'Fashion Business is a Business that sells clothes and other related products such as shoes','goods'),
(17, 'entartainment', 'Fashion Business is a Business that sells clothes and other related products such as shoes','goods'),
(18, 'beauty-spas', 'Fashion Business is a Business that sells clothes and other related products such as shoes','goods'),
(19, 'phone-accessories', 'Fashion Business is a Business that sells clothes and other related products such as shoes','goods'),
(20, 'bath-cleaning', 'Fashion Business is a Business that sells clothes and other related products such as shoes','goods'),
(21, 'smart-home', 'Fashion Business is a Business that sells clothes and other related products such as shoes','goods'),
(22, 'entertainment', 'Fashion Business is a Business that sells clothes and other related products such as shoes','goods'),
(23, 'made-in-rwanda', 'Fashion Business is a Business that sells clothes and other related products such as shoes','goods'),
(24, 'things-to-do', 'type of activities to do for adult and kids','local'),
(25, 'jewelry', 'category for jewelries for all ','goods'),
(26, 'personal-services', 'category for jewelries for all ','local'),
(28, 'soccer', 'category for sport deals ','sport'),
(29, 'basket', 'category for sport deals ','sport'),
(30, 'athletics', 'category for sport deals','sport'),
(31, 'biking', 'category for sport deals','sport'),
(32, 'men-fashion', 'fashion for men only','goods');

INSERT INTO `country` (`id`, `name`, `code`) VALUES('','rwanda',250);

INSERT INTO `city` (`id`, `name`, `country`) VALUES('', 'kigali', 1),('', 'kamembe', 1),('', 'muhanga', 1),('', 'huye', 1),('', 'rubavu', 1),('', 'musanze', 1);

INSERT INTO `location` (`id`, `name`, `city`) VALUES('','kimironko',1),('','kacyiru',1),('','rusizi',2);

INSERT INTO `business` (`id`,`name`,`country`,	`city`,`category`,`user_id`,`location`) VALUES('', 'Go Boutique',1,1,1,1,1);




INSERT INTO `product_sub_category` (`id`, `name`, `category_id`) VALUES
(1, 'wedding deals', 2),
(2, 'parties', 2),
(3, 'swiming', 2);




INSERT INTO `product` (`id`, `name`, `business_id`, `category_id`, `tag`, `product_description`, `kinyarwanda_description`, `selling_price`, `buying_price`, `city`, `longitude`, `latitude`, `deal_type`, `checkin`, `checkout`, `sign`, `deal_end_status`, `today_price`, `promotion`, `sells`, `instock`, `image`, `product_city_location_id`, `sub_categor1`, `sub_categor2`, `sub_categor3`, `last_review`, `review_count`, `sum_rating`, `product_absolute_link`) VALUES
(1, 'Wyndham Boston Beacon ', 1, 20, 'Wyndham Boston Beacon Hill - Boston, MA ', 'Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA ', 'Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA ', 455, 456, 1, NULL, NULL, NULL, '2018-09-12 00:00:00.000000', NULL, NULL, NULL, NULL, 'Hotel at a Glance: Wyndham ', NULL, NULL, '', 2, '', '', NULL, NULL, NULL, NULL, NULL),
(2, 'Wyndham Boston Beacon', 1, 2, 'Wyndham Boston Beacon Hill - Boston, MA ', 'Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA ', 'Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA ', 455, 456, 1, NULL, NULL, NULL, '2018-09-12 00:00:00.000000', NULL, NULL, NULL, NULL, 'Hotel at a Glance: Wyndham ', NULL, NULL, '', 1, '', '', NULL, NULL, NULL, NULL, NULL),
(3, 'Wyndham Boston Beaco', 1, 16, 'Wyndham Boston Beacon Hill - Boston, MA ', 'Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA ', 'Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA ', 455, 456, 1, NULL, NULL, NULL, '2018-09-12 00:00:00.000000', NULL, NULL, NULL, NULL, 'Hotel at a Glance: Wyndham', NULL, NULL, '', 1, '', '', NULL, NULL, NULL, NULL, NULL),
(4, 'Wyndham Boston Beacon', 1, 16, 'Wyndham Boston Beacon Hill - Boston, MA ', 'Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA ', 'Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA ', 455, 456, 1, NULL, NULL, NULL, '2018-09-12 00:00:00.000000', NULL, NULL, NULL, NULL, 'Hotel at a Glance: Wyndham ', NULL, NULL, '', 1, '', '', NULL, NULL, NULL, NULL, NULL),
(5, 'Wyndham Boston Beacon', 1, 16, 'Wyndham Boston Beacon Hill - Boston, MA ', 'Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA ', 'Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA ', 455, 456, 1, NULL, NULL, NULL, '2018-09-12 00:00:00.000000', NULL, NULL, NULL, NULL, 'Hotel at a Glance: Wyndham', NULL, NULL, '', 1, '', '', NULL, NULL, NULL, NULL, NULL),
(6, 'Wyndham Boston Beacon', 1, 16, 'Wyndham Boston Beacon Hill - Boston, MA ', 'Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA ', 'Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA ', 455, 456, 1, NULL, NULL, NULL, '2018-09-12 00:00:00.000000', NULL, NULL, NULL, NULL, 'Hotel at a Glance: Wyndham', NULL, NULL, '', 1, '', '', NULL, NULL, NULL, NULL, NULL),
(7, 'Wyndham Boston Beacon', 1, 16, 'Wyndham Boston Beacon Hill - Boston, MA ', 'Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA ', 'Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA Wyndham Boston Beacon Hill - Boston, MA ', 455, 456, 1, NULL, NULL, NULL, '2018-09-12 00:00:00.000000', NULL, NULL, NULL, NULL, 'Hotel at a Glance: Wyndham', NULL, NULL, '', 1, '', '', NULL, NULL, NULL, NULL, NULL);

